<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/16 21:48:23

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'persistent' => true,
  'pooling' => true,
  'dsn' => 'mysql:host=localhost;dbname=Piwam',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'classname' => 'DebugPDO',
  'name' => 'doctrine',
)),);
