<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/12/16 21:50:07
$this->security = array (
  'index' => 
  array (
    'credentials' => 'list_status',
  ),
  'create' => 
  array (
    'credentials' => 'add_status',
  ),
  'new' => 
  array (
    'credentials' => 'add_status',
  ),
  'edit' => 
  array (
    'credentials' => 'edit_status',
  ),
  'delete' => 
  array (
    'credentials' => 'del_status',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
