<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/16 21:51:33
sfConfig::add(array(
  'mod_export_enabled' => true,
  'mod_export_view_class' => 'sfPHP',
  'mod_export_is_internal' => false,
));
