<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/12/16 21:51:15
$this->security = array (
  'index' => 
  array (
    'credentials' => 'list_due',
  ),
  'create' => 
  array (
    'credentials' => 'add_due',
  ),
  'new' => 
  array (
    'credentials' => 'add_due',
  ),
  'edit' => 
  array (
    'credentials' => 'edit_due',
  ),
  'delete' => 
  array (
    'credentials' => 'del_due',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
