<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/12/16 21:51:37
$this->security = array (
  'index' => 
  array (
    'credentials' => 'mailing',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
