<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/16 15:51:01
sfConfig::add(array(
  'mod_install_enabled' => true,
  'mod_install_view_class' => 'sfPHP',
  'mod_install_is_internal' => false,
));
