<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/16 21:51:21
sfConfig::add(array(
  'mod_duetype_enabled' => true,
  'mod_duetype_view_class' => 'sfPHP',
  'mod_duetype_is_internal' => false,
));
