<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/16 21:48:59
sfConfig::add(array(
  'mod_config_member_enabled' => true,
  'mod_config_member_view_class' => 'sfPHP',
  'mod_config_member_is_internal' => false,
));
