<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/12/16 15:51:01
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'checkconfig' => 
  array (
    'is_secure' => false,
  ),
  'configdatabase' => 
  array (
    'is_secure' => false,
  ),
  'end' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
