<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/16 21:51:15
sfConfig::add(array(
  'mod_due_enabled' => true,
  'mod_due_view_class' => 'sfPHP',
  'mod_due_is_internal' => false,
));
