<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/12/16 21:48:59
$this->security = array (
  'index' => 
  array (
    'credentials' => 'config_member',
  ),
  'edit' => 
  array (
    'credentials' => 'config_member',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
