<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/16 16:19:49
sfConfig::add(array(
  'mod_association_enabled' => true,
  'mod_association_view_class' => 'sfPHP',
  'mod_association_is_internal' => false,
));
