<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/16 15:51:01
sfConfig::add(array(
  'mod_login_enabled' => true,
  'mod_login_view_class' => 'sfPHP',
  'mod_login_is_internal' => false,
));
