<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/16 16:20:32
sfConfig::add(array(
  'mod_member_enabled' => true,
  'mod_member_view_class' => 'sfPHP',
  'mod_member_is_internal' => false,
));
