<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/12/16 21:51:21
$this->security = array (
  'index' => 
  array (
    'credentials' => 'config_dues',
  ),
  'create' => 
  array (
    'credentials' => 'config_dues',
  ),
  'new' => 
  array (
    'credentials' => 'config_dues',
  ),
  'edit' => 
  array (
    'credentials' => 'config_dues',
  ),
  'delete' => 
  array (
    'credentials' => 'config_dues',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
