<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/16 21:50:07
sfConfig::add(array(
  'mod_status_enabled' => true,
  'mod_status_view_class' => 'sfPHP',
  'mod_status_is_internal' => false,
));
