<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/16 21:51:37
sfConfig::add(array(
  'mod_mailing_enabled' => true,
  'mod_mailing_view_class' => 'sfPHP',
  'mod_mailing_is_internal' => false,
));
